version: '3.9'
services:
  notion-tracker:
    build: .
    platform: linux/amd64
    restart: always
    volumes:
      - ${PWD}/config/settings.local.yml:/app/config/settings.local.yml
    entrypoint: ["bundle", "exec", "sidekiq"]
    env_file:
      - .env.production
    networks:
      - notion-tracker-network
  redis:
    image: redis:5
    restart: always
    volumes:
      - notion-tracker-redis:/data
    networks:
      - notion-tracker-network

networks:
  notion-tracker-network:
volumes:
  notion-tracker-redis:
