notion:
  definition_fields:
    deadline: "Deadline"
    end_time: "Do on end"
    is_done: "Done?"
    recurring_type: "Repeat"
    task_name: "What to do"
    time_mark: "Do on"
  databases:
    tasks: ""
